{% set name = "SPHY" %}
{% set version = "2.2.1" %}
{% set sha256 = "004d1eb10b159e2617f88a6bbc186e758b4df83351f1882a9bd5ad0aaa4af462" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub remove the line above
  # uncomment the line below and modify as needed
  # url: https://github.com/simplejson/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Uncomment the following line if the package is pure python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/meta.html#building-noarch-packages for more details.
  noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas>=0.20.1
    - numpy>=1.16.2

test:
  imports:
    - SPHY

about:
  home: https://github.com/WilcoTerink/SPHY
  license: GNU General Public License v3 (GPL-3.0)
  license_family: GPL
  summary: Spatial Processes in HYdrology (SPHY) model
  description: "Repository for the Spatial Proceses in HYdrology (SPHY) model\r\n=============================================================\r\n\r\nThe documentation can be found here: https://sphy.readthedocs.io/en/latest/.\r\
    \n"
  doc_url: ''
  dev_url: ''
